name: Build and Deploy on my server

on:
  push:
    branches:
      - main
  # 可选：添加 pull_request 支持
  # pull_request:
  #   branches:
  #     - main

# env:
#   NODE_VERSION: "18"
#   BUILD_DIR: ${{ vars.BUILD_DIR }}
#   DEPLOY_USER: ${{ vars.USER }}
#   DEPLOY_SERVER: ${{ secrets.SERVER }}
#   DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ vars.BUILD_DIR }}

      - name: Check Build Dir
        run: |
          pwd
          ls -a ${{ vars.BUILD_DIR }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy to Aliyun server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ env.aliyun.secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ vars.USER }}
          TARGET: ${{ vars.DEPLOY_PATH }}
          #EXCLUDE: "/dist/, /node_modules/"#
          SCRIPT_BEFORE: |
            ls -a
          SCRIPT_AFTER: |
            ls -a
            echo $RSYNC_STDOUT

      - name: Deploy to Huaweiyun server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ env.aliyun.secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ vars.USER }}
          TARGET: ${{ vars.DEPLOY_PATH }}
          #EXCLUDE: "/dist/, /node_modules/"#
          SCRIPT_BEFORE: |
            ls -a
          SCRIPT_AFTER: |
            ls -a
            echo $RSYNC_STDOUT
